/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package Global.eda.sb.model.impl;

import Global.eda.sb.model.GlobalEda;
import Global.eda.sb.model.GlobalEdaModel;
import Global.eda.sb.model.GlobalEdaSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the GlobalEda service. Represents a row in the &quot;EDA_GlobalEda&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>GlobalEdaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GlobalEdaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GlobalEdaImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class GlobalEdaModelImpl
	extends BaseModelImpl<GlobalEda> implements GlobalEdaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a global eda model instance should use the <code>GlobalEda</code> interface instead.
	 */
	public static final String TABLE_NAME = "EDA_GlobalEda";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"fooId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"field1", Types.VARCHAR}, {"field2", Types.BOOLEAN},
		{"field3", Types.INTEGER}, {"field4", Types.TIMESTAMP},
		{"field5", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fooId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("field1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("field2", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("field3", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("field4", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("field5", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EDA_GlobalEda (uuid_ VARCHAR(75) null,fooId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,field1 VARCHAR(75) null,field2 BOOLEAN,field3 INTEGER,field4 DATE null,field5 VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table EDA_GlobalEda";

	public static final String ORDER_BY_JPQL = " ORDER BY globalEda.field1 ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EDA_GlobalEda.field1 ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long FIELD2_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long FIELD1_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static GlobalEda toModel(GlobalEdaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		GlobalEda model = new GlobalEdaImpl();

		model.setUuid(soapModel.getUuid());
		model.setFooId(soapModel.getFooId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setField1(soapModel.getField1());
		model.setField2(soapModel.isField2());
		model.setField3(soapModel.getField3());
		model.setField4(soapModel.getField4());
		model.setField5(soapModel.getField5());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<GlobalEda> toModels(GlobalEdaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<GlobalEda> models = new ArrayList<GlobalEda>(soapModels.length);

		for (GlobalEdaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public GlobalEdaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fooId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFooId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fooId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GlobalEda.class;
	}

	@Override
	public String getModelClassName() {
		return GlobalEda.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GlobalEda, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GlobalEda, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GlobalEda, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((GlobalEda)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GlobalEda, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GlobalEda, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GlobalEda)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GlobalEda, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GlobalEda, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, GlobalEda>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			GlobalEda.class.getClassLoader(), GlobalEda.class,
			ModelWrapper.class);

		try {
			Constructor<GlobalEda> constructor =
				(Constructor<GlobalEda>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<GlobalEda, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<GlobalEda, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<GlobalEda, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<GlobalEda, Object>>();
		Map<String, BiConsumer<GlobalEda, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<GlobalEda, ?>>();

		attributeGetterFunctions.put("uuid", GlobalEda::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<GlobalEda, String>)GlobalEda::setUuid);
		attributeGetterFunctions.put("fooId", GlobalEda::getFooId);
		attributeSetterBiConsumers.put(
			"fooId", (BiConsumer<GlobalEda, Long>)GlobalEda::setFooId);
		attributeGetterFunctions.put("groupId", GlobalEda::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<GlobalEda, Long>)GlobalEda::setGroupId);
		attributeGetterFunctions.put("companyId", GlobalEda::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<GlobalEda, Long>)GlobalEda::setCompanyId);
		attributeGetterFunctions.put("userId", GlobalEda::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<GlobalEda, Long>)GlobalEda::setUserId);
		attributeGetterFunctions.put("userName", GlobalEda::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<GlobalEda, String>)GlobalEda::setUserName);
		attributeGetterFunctions.put("createDate", GlobalEda::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<GlobalEda, Date>)GlobalEda::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", GlobalEda::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<GlobalEda, Date>)GlobalEda::setModifiedDate);
		attributeGetterFunctions.put("field1", GlobalEda::getField1);
		attributeSetterBiConsumers.put(
			"field1", (BiConsumer<GlobalEda, String>)GlobalEda::setField1);
		attributeGetterFunctions.put("field2", GlobalEda::getField2);
		attributeSetterBiConsumers.put(
			"field2", (BiConsumer<GlobalEda, Boolean>)GlobalEda::setField2);
		attributeGetterFunctions.put("field3", GlobalEda::getField3);
		attributeSetterBiConsumers.put(
			"field3", (BiConsumer<GlobalEda, Integer>)GlobalEda::setField3);
		attributeGetterFunctions.put("field4", GlobalEda::getField4);
		attributeSetterBiConsumers.put(
			"field4", (BiConsumer<GlobalEda, Date>)GlobalEda::setField4);
		attributeGetterFunctions.put("field5", GlobalEda::getField5);
		attributeSetterBiConsumers.put(
			"field5", (BiConsumer<GlobalEda, String>)GlobalEda::setField5);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getFooId() {
		return _fooId;
	}

	@Override
	public void setFooId(long fooId) {
		_fooId = fooId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getField1() {
		if (_field1 == null) {
			return "";
		}
		else {
			return _field1;
		}
	}

	@Override
	public void setField1(String field1) {
		_columnBitmask = -1L;

		_field1 = field1;
	}

	@JSON
	@Override
	public boolean getField2() {
		return _field2;
	}

	@JSON
	@Override
	public boolean isField2() {
		return _field2;
	}

	@Override
	public void setField2(boolean field2) {
		_columnBitmask |= FIELD2_COLUMN_BITMASK;

		if (!_setOriginalField2) {
			_setOriginalField2 = true;

			_originalField2 = _field2;
		}

		_field2 = field2;
	}

	public boolean getOriginalField2() {
		return _originalField2;
	}

	@JSON
	@Override
	public int getField3() {
		return _field3;
	}

	@Override
	public void setField3(int field3) {
		_field3 = field3;
	}

	@JSON
	@Override
	public Date getField4() {
		return _field4;
	}

	@Override
	public void setField4(Date field4) {
		_field4 = field4;
	}

	@JSON
	@Override
	public String getField5() {
		if (_field5 == null) {
			return "";
		}
		else {
			return _field5;
		}
	}

	@Override
	public void setField5(String field5) {
		_field5 = field5;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(GlobalEda.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), GlobalEda.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GlobalEda toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GlobalEdaImpl globalEdaImpl = new GlobalEdaImpl();

		globalEdaImpl.setUuid(getUuid());
		globalEdaImpl.setFooId(getFooId());
		globalEdaImpl.setGroupId(getGroupId());
		globalEdaImpl.setCompanyId(getCompanyId());
		globalEdaImpl.setUserId(getUserId());
		globalEdaImpl.setUserName(getUserName());
		globalEdaImpl.setCreateDate(getCreateDate());
		globalEdaImpl.setModifiedDate(getModifiedDate());
		globalEdaImpl.setField1(getField1());
		globalEdaImpl.setField2(isField2());
		globalEdaImpl.setField3(getField3());
		globalEdaImpl.setField4(getField4());
		globalEdaImpl.setField5(getField5());

		globalEdaImpl.resetOriginalValues();

		return globalEdaImpl;
	}

	@Override
	public int compareTo(GlobalEda globalEda) {
		int value = 0;

		value = getField1().compareTo(globalEda.getField1());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GlobalEda)) {
			return false;
		}

		GlobalEda globalEda = (GlobalEda)obj;

		long primaryKey = globalEda.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		GlobalEdaModelImpl globalEdaModelImpl = this;

		globalEdaModelImpl._originalUuid = globalEdaModelImpl._uuid;

		globalEdaModelImpl._originalGroupId = globalEdaModelImpl._groupId;

		globalEdaModelImpl._setOriginalGroupId = false;

		globalEdaModelImpl._originalCompanyId = globalEdaModelImpl._companyId;

		globalEdaModelImpl._setOriginalCompanyId = false;

		globalEdaModelImpl._setModifiedDate = false;

		globalEdaModelImpl._originalField2 = globalEdaModelImpl._field2;

		globalEdaModelImpl._setOriginalField2 = false;

		globalEdaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<GlobalEda> toCacheModel() {
		GlobalEdaCacheModel globalEdaCacheModel = new GlobalEdaCacheModel();

		globalEdaCacheModel.uuid = getUuid();

		String uuid = globalEdaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			globalEdaCacheModel.uuid = null;
		}

		globalEdaCacheModel.fooId = getFooId();

		globalEdaCacheModel.groupId = getGroupId();

		globalEdaCacheModel.companyId = getCompanyId();

		globalEdaCacheModel.userId = getUserId();

		globalEdaCacheModel.userName = getUserName();

		String userName = globalEdaCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			globalEdaCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			globalEdaCacheModel.createDate = createDate.getTime();
		}
		else {
			globalEdaCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			globalEdaCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			globalEdaCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		globalEdaCacheModel.field1 = getField1();

		String field1 = globalEdaCacheModel.field1;

		if ((field1 != null) && (field1.length() == 0)) {
			globalEdaCacheModel.field1 = null;
		}

		globalEdaCacheModel.field2 = isField2();

		globalEdaCacheModel.field3 = getField3();

		Date field4 = getField4();

		if (field4 != null) {
			globalEdaCacheModel.field4 = field4.getTime();
		}
		else {
			globalEdaCacheModel.field4 = Long.MIN_VALUE;
		}

		globalEdaCacheModel.field5 = getField5();

		String field5 = globalEdaCacheModel.field5;

		if ((field5 != null) && (field5.length() == 0)) {
			globalEdaCacheModel.field5 = null;
		}

		return globalEdaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GlobalEda, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GlobalEda, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GlobalEda, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((GlobalEda)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GlobalEda, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GlobalEda, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GlobalEda, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((GlobalEda)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, GlobalEda>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _fooId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _field1;
	private boolean _field2;
	private boolean _originalField2;
	private boolean _setOriginalField2;
	private int _field3;
	private Date _field4;
	private String _field5;
	private long _columnBitmask;
	private GlobalEda _escapedModel;

}