/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package noticias.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Noticia service. Represents a row in the &quot;EDA_Noticia&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>noticias.sb.model.impl.NoticiaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>noticias.sb.model.impl.NoticiaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Noticia
 * @generated
 */
@ProviderType
public interface NoticiaModel extends BaseModel<Noticia> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a noticia model instance should use the {@link Noticia} interface instead.
	 */

	/**
	 * Returns the primary key of this noticia.
	 *
	 * @return the primary key of this noticia
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this noticia.
	 *
	 * @param primaryKey the primary key of this noticia
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this noticia.
	 *
	 * @return the uuid of this noticia
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this noticia.
	 *
	 * @param uuid the uuid of this noticia
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the noticia ID of this noticia.
	 *
	 * @return the noticia ID of this noticia
	 */
	public long getNoticiaId();

	/**
	 * Sets the noticia ID of this noticia.
	 *
	 * @param noticiaId the noticia ID of this noticia
	 */
	public void setNoticiaId(long noticiaId);

	/**
	 * Returns the user ID of this noticia.
	 *
	 * @return the user ID of this noticia
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this noticia.
	 *
	 * @param userId the user ID of this noticia
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this noticia.
	 *
	 * @return the user uuid of this noticia
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this noticia.
	 *
	 * @param userUuid the user uuid of this noticia
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this noticia.
	 *
	 * @return the user name of this noticia
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this noticia.
	 *
	 * @param userName the user name of this noticia
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this noticia.
	 *
	 * @return the create date of this noticia
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this noticia.
	 *
	 * @param createDate the create date of this noticia
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this noticia.
	 *
	 * @return the modified date of this noticia
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this noticia.
	 *
	 * @param modifiedDate the modified date of this noticia
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the titulo of this noticia.
	 *
	 * @return the titulo of this noticia
	 */
	@AutoEscape
	public String getTitulo();

	/**
	 * Sets the titulo of this noticia.
	 *
	 * @param titulo the titulo of this noticia
	 */
	public void setTitulo(String titulo);

	/**
	 * Returns the descricao of this noticia.
	 *
	 * @return the descricao of this noticia
	 */
	@AutoEscape
	public String getDescricao();

	/**
	 * Sets the descricao of this noticia.
	 *
	 * @param descricao the descricao of this noticia
	 */
	public void setDescricao(String descricao);

	/**
	 * Returns the document ID of this noticia.
	 *
	 * @return the document ID of this noticia
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this noticia.
	 *
	 * @param documentId the document ID of this noticia
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the file url of this noticia.
	 *
	 * @return the file url of this noticia
	 */
	@AutoEscape
	public String getFileUrl();

	/**
	 * Sets the file url of this noticia.
	 *
	 * @param fileUrl the file url of this noticia
	 */
	public void setFileUrl(String fileUrl);

}